-- MySQL Script generated by MySQL Workbench
-- Wed Mar 21 17:50:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema planning_manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema planning_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `planning_manager` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema planning_manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema planning_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `planning_manager` DEFAULT CHARACTER SET latin1 ;
USE `planning_manager` ;

-- -----------------------------------------------------
-- Table `planning_manager`.`T_Teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `planning_manager`.`T_Teams` ;

CREATE TABLE IF NOT EXISTS `planning_manager`.`T_Teams` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(64) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planning_manager`.`T_UserGroups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `planning_manager`.`T_UserGroups` ;

CREATE TABLE IF NOT EXISTS `planning_manager`.`T_UserGroups` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(64) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planning_manager`.`T_Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `planning_manager`.`T_Users` ;

CREATE TABLE IF NOT EXISTS `planning_manager`.`T_Users` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(64) NULL,
  `LastName` VARCHAR(64) NOT NULL,
  `T_Teams_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `T_Teams_Id`),
  INDEX `fk_T_Users_T_Teams1_idx` (`T_Teams_Id` ASC),
  CONSTRAINT `fk_T_Users_T_Teams1`
    FOREIGN KEY (`T_Teams_Id`)
    REFERENCES `planning_manager`.`T_Teams` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planning_manager`.`T_Users_has_T_UserGroups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `planning_manager`.`T_Users_has_T_UserGroups` ;

CREATE TABLE IF NOT EXISTS `planning_manager`.`T_Users_has_T_UserGroups` (
  `T_Users_Id` INT NOT NULL,
  `T_UserGroups_Id` INT NOT NULL,
  PRIMARY KEY (`T_Users_Id`, `T_UserGroups_Id`),
  INDEX `fk_T_Users_has_T_UserGroups_T_UserGroups1_idx` (`T_UserGroups_Id` ASC),
  INDEX `fk_T_Users_has_T_UserGroups_T_Users1_idx` (`T_Users_Id` ASC),
  CONSTRAINT `fk_T_Users_has_T_UserGroups_T_Users1`
    FOREIGN KEY (`T_Users_Id`)
    REFERENCES `planning_manager`.`T_Users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_Users_has_T_UserGroups_T_UserGroups1`
    FOREIGN KEY (`T_UserGroups_Id`)
    REFERENCES `planning_manager`.`T_UserGroups` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `planning_manager` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
